DEBUG = True
MAX_REPOS_TO_PROCESS = 12 if DEBUG else 2 ** 32  # applied in DEBUG only

ORGANIZATION_NAME = "DiPaolo"
ORGANIZATION_DOMAIN = 'dipaolo.dev'
APPLICATION_NAME = 'Git Stats Plate Generator'
APPLICATION_NAME_LOWERCASE = 'git_stats_plate_gen'

# defaults
DEFAULT_USE_CACHE = True
DEFAULT_OUT_IMAGE_BASE_NAME = 'github_lang_stats'
DEFAULT_MIN_PERCENT = 1.0

# image
DEFAULT_IMAGE_WIDTH = 1280
DEFAULT_IMAGE_HEIGHT = 720
INTERNAL_IMAGE_TYPE = 'png'
